Move ViewComponent to separate GitHub organization.
ViewComponent/view_component pull request #1496
Opened 2022-08-25 21:09 UTC by joelhawksley

Closes #1424

### What are you trying to accomplish?

This PR updates our docs ahead of moving ViewComponent to its own organization on GitHub ❤️

2022-08-25 21:37 UTC, Spone requested changes

2022-08-25 21:37 UTC, Spone commented on docs/CONTRIBUTING.md
> +If you have any substantial changes that you would like to make, please [open an issue](http://github.com/viewcomponent/view_componentmponent/issues/new) first to discuss them with us.
```suggestion
If you have any substantial changes that you would like to make, please [open an issue](http://github.com/viewcomponent/view_component/issues/new) first to discuss them with us.
```

2022-08-26 08:06 UTC, boardfish approved these changes

2022-08-26 08:48 UTC, Spone approved these changes

2022-08-29 16:46 UTC, rmacklin reviewed
Looks like 11d5ac8d6e13acf54eb1c2ab6e9359fbc254109c may have been unintentionally dropped, and the same typo was introduced in another file in b8efb570c24ee973295e798177421e2ff8116f57

2022-08-29 16:46 UTC, rmacklin commented on docs/CHANGELOG.md
> +**ViewComponent has moved to a new organization: [https://github.com/viewcomponent/view_component](https://github.com/viewcomponent/view_component). See [https://github.com/viewcomponent/view_compone
```suggestion
**ViewComponent has moved to a new organization: [https://github.com/viewcomponent/view_component](https://github.com/viewcomponent/view_component). See [https://github.com/viewcomponent/view_component/issues/1424](https://github.com/viewcomponent/view_component/issues/1424) for more details.**
```

2022-08-29 16:46 UTC, rmacklin commented on docs/CONTRIBUTING.md
> +If you have any substantial changes that you would like to make, please [open an issue](http://github.com/viewcomponent/view_componentmponent/issues/new) first to discuss them with us.
```suggestion
If you have any substantial changes that you would like to make, please [open an issue](http://github.com/viewcomponent/view_component/issues/new) first to discuss them with us.
```

2022-08-31 17:35 UTC, merged