[Docs]Update document for changing view_component_path
ViewComponent/view_component pull request #1870
Opened 2023-10-14 04:46 UTC by hachi8833

### What are you trying to accomplish?

I'm trying to update the document so that users can change the `view_component_path`.

### What approach did you choose and why?

I got stuck when I tried to introduce ViewComponent to Rails 7.1 app because changing just `config.view_component.view_component_path` did not work.

Finally I found that `config.eager_load_paths` should also be changed with the same path to get this change work.

I checked the fact with the newly generated Rails 7.1/7.0/6.1 app.

2023-10-14 09:32 UTC, Spone commented
Thanks for reporting this! I'm wondering if we can inject the `view_component_path` into the `eager_load_paths` when needed, so the users don't need to do it themselves.

2023-10-15 06:20 UTC, hachi8833 commented
Sounds a better idea!
If rhe auto-injection is supported, the PR can be closed instead.

2023-10-15 12:18 UTC, Spone commented
Would you like to try it and open a PR for the changes?

2023-10-16 00:55 UTC, hachi8833 commented
After that I change my mind: just adding the documents might be safer because the eager-loading config is explicit and we don't need to change the current code.

I'm a bit worried about changing the code might affect some patches to ViewComponent such as following:

https://github.com/palkan/view_component-contrib

2023-10-16 15:50 UTC, reeganviljoen commented
Maybe we can get the view_component_contrib maintaners to join this discussion, they may be keen to add this to their lib too

2023-10-16 15:51 UTC, reeganviljoen commented
@spone @camertron Since this could be a breaking change I suggest that maybe we add this to v4 checklist

2023-10-16 16:52 UTC, camertron commented
What specifically would be the danger in automatically adding the `view_component_path` to the list of eager load paths? Seems like a pretty safe thing to do, unless I'm really missing something?

2023-10-16 19:02 UTC, reeganviljoen commented
From what I understand their is a bit of concern that existing community patches may break but on further thought we can't gurantee the stability of other libraries that patch vc

2023-10-17 17:09 UTC, camertron commented
@reeganviljoen right yeah, I'm curious about the specific issues community patches would have if ViewComponent were to automatically append to the set of Rails eager load paths. It's possible we need to do some investigation here.

2023-10-18 17:39 UTC, camertron requested changes

2023-10-18 17:39 UTC, camertron commented on docs/guide/generators.md
> +    config.eager_load_paths << Rails.root.join("app/views/components")
```suggestion
config.view_component.view_component_path = "app/views/components"
config.eager_load_paths << Rails.root.join("app/views/components")
```

2023-10-18 18:52 UTC, camertron approved these changes

2023-10-18 18:53 UTC, camertron commented
Going to merge this for now since it's just a documentation change 👍

2023-10-18 18:53 UTC, merged