Don't add ActionDispatch::Static middleware continued
ViewComponent/view_component pull request #1892
Opened 2023-11-01 06:55 UTC by reeganviljoen

### What are you trying to accomplish?

I am attempting to finish #1091 by adding prism through a cdn when no asset pipeline is present

### What approach did you choose and why?

When their is no asset pipeline I decided to serve prism through a cdn

2023-11-01 21:25 UTC, camertron requested changes
Thanks for picking this up @reeganviljoen!

2023-11-01 21:25 UTC, camertron commented on app/helpers/preview_helper.rb
> +  FALLBACK_LANGUAGE = "ruby"\
```suggestion
  FALLBACK_LANGUAGE = "ruby"
```

2023-11-01 21:25 UTC, camertron commented on app/helpers/preview_helper.rb
> +  def prism_css_source
```suggestion
  def prism_css_source_url
```

2023-11-01 21:25 UTC, camertron commented on app/helpers/preview_helper.rb
> +  def prism_js_source
```suggestion
  def prism_js_source_url
```

2023-11-01 21:25 UTC, camertron commented on app/helpers/preview_helper.rb
> +  def serve_static_previews?
```suggestion
  def serve_static_preview_assets?
```

2023-11-01 21:25 UTC, camertron commented on lib/view_component/engine.rb
> +    def serve_static_previews?(app_config)
Can this be extracted into a module perhaps?

```suggestion
    def serve_static_preview_assets?(app_config)
```

2023-11-04 21:06 UTC, reeganviljoen commented
@camertron can you please re-review this when you can :pray:

2023-11-06 23:54 UTC, camertron approved these changes
Thanks @reeganviljoen, looks good 👍

2023-11-07 08:56 UTC, reeganviljoen commented
@camertron Its been rebased and is ready to merge 🙏

2023-11-07 10:10 UTC, Spone requested changes

2023-11-07 19:21 UTC, camertron approved these changes

2023-11-07 19:22 UTC, merged