Search for the Rails module in the root namespace
ViewComponent/view_component pull request #1894
Opened 2023-11-02 11:00 UTC by Zeneixe

Fix for the issue described here: https://github.com/ViewComponent/view_component/issues/1891

```
NoMethodError: undefined method `env' for MyProject::Rails:Module (NoMethodError)

    if Rails.env.development? || Rails.env.test?
            ^^^^
/home/circleci/project/vendor/bundle/ruby/3.2.0/gems/view_component-3.7.0/lib/view_component/base.rb:222:in `<class:Base>'
```

The issue started with version `3.6.0`, the code above was introduced with this PR: https://github.com/ViewComponent/view_component/pull/1841

### What are you trying to accomplish?

Fix the issue

### What approach did you choose and why?

By specifying the root namespace for `Rails` we avoid the ambiguity. It seems to be the simplest possible fix at hand

2023-11-02 16:38 UTC, Spone commented
Hi @Zeneixe thanks for the PR. Could you please add a CHANGELOG entry for this fix?

2023-11-02 16:38 UTC, Spone approved these changes

2023-11-03 12:30 UTC, Spone requested changes

2023-11-03 12:30 UTC, Spone commented on docs/CHANGELOG.md
> +* Fix bug where the `Rails` module wasn't being searched from the root namespace
```suggestion
* Fix bug where the `Rails` module wasn't being searched from the root namespace.
```

2023-11-03 16:50 UTC, Spone approved these changes

2023-11-03 17:53 UTC, camertron approved these changes

2023-11-03 17:53 UTC, merged