Add experimental support for default slot values
ViewComponent/view_component pull request #2063
Opened 2024-07-30 18:16 UTC by joelhawksley

### What are you trying to accomplish?

This PR aims to close #1861 and #614, implementing an experimental approach for default slot values.

### What approach did you choose and why?

I added an experimental module that must be included to use the feature, adopting the API suggested by @BlakeWilliams in https://github.com/ViewComponent/view_component/pull/1861#issuecomment-1785454288.

### Anything you want to highlight for special attention from reviewers?

Do we want to allow default value(s) for `renders_many` slots? I don't think we need to solve it now, but something to consider adding later.

2024-07-30 19:29 UTC, reeganviljoen commented
@joelhawksley would you mind adding docs about this, as I feel users would genuinely like this ❤️

2024-07-30 20:17 UTC, Spone requested changes
Great to see this addition! Nice API :)

2024-07-30 20:17 UTC, Spone commented on test/sandbox/test/slotable_test.rb
> +  def test_slotable_default
Shouldn't we test that specifying the slot correctly overrides the default?

2024-07-30 22:00 UTC, joelhawksley commented
@reeganviljoen done, let me know what you think! https://github.com/ViewComponent/view_component/pull/2063/files#diff-867de23963ba79a34d995f1d16db1d42da92c63d86481bf59031a7d0ebc6f837

2024-07-31 18:52 UTC, reeganviljoen approved these changes
@joelhawksley LGTM🚀

2024-08-01 20:31 UTC, Spone approved these changes
👌

2024-08-01 20:44 UTC, merged